#!/bin/python3

def function(n):
    if n%2!=0:
        print ("Weird")
    elif n>=2 and n<=5:
        print ("Not Weird")
    elif n>=6 and n<=20:
        print ("Weird")
    elif n>20:
        print ("Not Weird")
        
function(number = int(input()))
